image:
  repository: pltvs/mongodb-gcs-backup
  tag: latest
  pullPolicy: IfNotPresent

secretName:

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

env:
  GCS_BUCKET:
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  MONGODB_DB:
  SLACK_ALERTS:
  SLACK_WEBHOOK_URL:
  SLACK_CHANNEL:
  SLACK_USERNAME:

concurrencyPolicy: Forbid
failedJobsHistoryLimit: 1
restartPolicy: OnFailure
schedule: "* * * * *"
successfulJobsHistoryLimit: 3
